# Site settings
title: dignwork
email: stephen.espinola@gmail.com
description: dignwork empowers people to find meaningful, rewarding work by providing quality information and tools
# baseurl: "/jekyll-smart-material" # the subpath of your site, e.g. /blog/
url: "https://steveespinola.github.io" # the base hostname & protocol for your site
copyright: '&copy; 2015-2016 Smart Material Theme'

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: blue-deep_orange

# Google Analytics account ID (UA-XXXXXXXX-X)

# google-analytics-ua: UA-84475574-1
